name       : clr-boot-manager
version    : 3.2.9
release    : 25
source     :
    - https://github.com/clearlinux/clr-boot-manager/releases/download/v3.2.9/clr-boot-manager-3.2.9.tar.xz : 39e1688b3d2284a4cc4104b5d1d304c3f5bb3bfe73e4d3c19af209b34a467162 
license    : LGPL-2.1-or-later
component  : system.base
summary    : Kernel & Boot Loader Management
description: |
    clr-boot-manager exists to enable the correct maintenance of vendor kernels and appropriate garbage collection tactics over the course of upgrades. The implementation provides the means to enable correct cohabitation on a shared boot directory, such as the EFI System Partition for UEFI-booting operating systems.

    Special care is taken to ensure the ESP is handled gracefully, and in the instance that it is not already mounted, then clr-boot-manager will automatically discover and mount it, and automatically unmount the ESP again when it is complete.

    Most importantly, clr-boot-manager provides a simple mechanism to provide kernel updates, with the ability for users to rollback to an older kernel should the new update be problematic. This is achieved through the use of strict namespace policies, permanent source paths, and clr-boot-manager's own internal logic, without the need for "meta packages" or undue complexity on the distribution side.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(check)
setup      : |
    # Fix LUKS
    %patch -p1 < $pkgfiles/0001-globbrace.patch

    %meson_configure -Dwith-vendor-prefix=Solus \
                     -Dwith-kernel-modules-dir=/lib/modules \
                     -Dwith-kernel-namespace=com.solus-project \
                     -Dwith-bootloader=systemd-boot
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Pre-enable the booted service
    install -Ddm00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../clr-boot-manager-booted.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
