name       : clr-boot-manager
version    : 3.2.12
release    : 29
source     :
    - https://github.com/clearlinux/clr-boot-manager/archive/refs/tags/v3.2.12.tar.gz : 9b5df76a980b5edfbf3369ed22db4b23cc720446612014516f23cdb2ee1e9a47
    - https://github.com/intel/libnica/archive/f779ca10.tar.gz : 9186874fad01f2a73bfd4eb396137e8c34cf47adc2c74cdd4a6fcf92591b7930
license    : LGPL-2.1-or-later
component  : system.base
summary    : Kernel & Boot Loader Management
description: |
    clr-boot-manager exists to enable the correct maintenance of vendor kernels and appropriate garbage collection tactics over the course of upgrades. The implementation provides the means to enable correct cohabitation on a shared boot directory, such as the EFI System Partition for UEFI-booting operating systems.

    Special care is taken to ensure the ESP is handled gracefully, and in the instance that it is not already mounted, then clr-boot-manager will automatically discover and mount it, and automatically unmount the ESP again when it is complete.

    Most importantly, clr-boot-manager provides a simple mechanism to provide kernel updates, with the ability for users to rollback to an older kernel should the new update be problematic. This is achieved through the use of strict namespace policies, permanent source paths, and clr-boot-manager's own internal logic, without the need for "meta packages" or undue complexity on the distribution side.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(check)
    - pkgconfig(efivar)
    - gnu-efi-devel
rundeps    :
    - shim-signed
setup      : |
    %apply_patches

    # Copy libnica
    tar -C src/libnica -xf $sources/f779ca10.tar.gz --strip-components=1

    %meson_configure -Dwith-vendor-prefix=Solus \
                     -Dwith-kernel-modules-dir=/lib/modules \
                     -Dwith-kernel-namespace=com.solus-project \
                     -Dwith-bootloader=shim-systemd-boot \
                     -Dwith-uefi-entry-label="Solus Linux Bootloader"
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Pre-enable the booted service
    install -Ddm00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../clr-boot-manager-booted.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
