name       : clr-boot-manager
version    : 1.5.5
release    : 19
source     :
    - https://github.com/clearlinux/clr-boot-manager/releases/download/v1.5.5/clr-boot-manager-1.5.5.tar.xz : 487ed0e0a6e9e0aebd6cd9bb0573e6ea60a5de51eec6956cd9c8b7fa3ae79a9b
license    :
    - LGPL-2.1
component  : system.base
summary    : Kernel & Boot Loader Management
description: |
    clr-boot-manager exists to enable the correct maintenance of vendor kernels and appropriate garbage collection tactics over the course of upgrades. The implementation provides the means to enable correct cohabitation on a shared boot directory, such as the EFI System Partition for UEFI-booting operating systems.

    Special care is taken to ensure the ESP is handled gracefully, and in the instance that it is not already mounted, then clr-boot-manager will automatically discover and mount it, and automatically unmount the ESP again when it is complete.

    Most importantly, clr-boot-manager provides a simple mechanism to provide kernel updates, with the ability for users to rollback to an older kernel should the new update be problematic. This is achieved through the use of strict namespace policies, permanent source paths, and clr-boot-manager's own internal logic, without the need for "meta packages" or undue complexity on the distribution side.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(check)
setup      : |
    # Ensure we properly clean up module trees
    pushd src/libnica
    %patch -p1 < $pkgfiles/nica-rm-rf.patch
    popd
    
    # In future, we'll drop goofiboot and go to systemd-boot
    %configure --with-vendor-prefix=Solus \
               --with-kernel-modules-dir=/lib/modules \
               --with-kernel-namespace=com.solus-project \
               --with-bootloader=systemd-boot
build      : |
    %make
install    : |
    %make_install
    # Pre-enable the booted service
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../clr-boot-manager-booted.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
